### ISSUE TITLE
Dependency Error during Gazebo and Turtlebot Simulator Installation

### ISSUE THREAD

**Issue by hofes** [turtlebot/turtlebot_simulator#18]
We are facing troubles installing the turtlebot-simulator package via apt-get with 
sudo apt-get install ros-hydro-turtlebot-simulator

The error we get is:
Depends: ros-hydro-turtlebot-gazebo but it is not going to be installed

If going on and trying to install ros-hydro-turtlebot-gazebo leads to other missing packages.

We also tried to install according to the gazebo website (http://gazebosim.org/wiki/1.9/install and http://gazebosim.org/wiki/Tutorials/1.9/Installing_gazebo_ros_Packages)
but then we faced some dependency issues with sdformat and libsdformat because the ros-hydro-turetlebot-gazebo wants to install gazebo-current and sdformat but gazebo-current install libsdformat which interferes with libsdformat.

Did anyone else face similar issues?

**Comment by tfoote** [comment]
You cannot use gazebo-current (currently 2.0) and ROS binaries built on top of gazebo (1.9.x) together. If you want to install ros-hydro packages which depends on gazebo you will need to switch to having gazebo installed instead of gazebo-current. 

http://gazebosim.org/wiki/Install/Gazebo_and_ROS

@hsu @nkoenig It might be good to update this tutorial to mention how to use the gazebo-current versions: http://gazebosim.org/wiki/Tutorials/1.9/Installing_gazebo_ros_Packages I've added a link to mention that it doesn't work with gazebo-current( aka 2.0)
