### ISSUE TITLE
install on indigo

### ISSUE THREAD

**Issue by vliedel** [turtlebot/turtlebot_simulator#26]
Hi i'm trying to compile the indigo branch, but for some reason catkin doesn't even seem to try compiling turtlebot_simulator. When I do catkin_make --force-cmake, i do see turtlebot_simulator in the "traversing .. packages" list, however the package is not found when i try to roscd, or try to tab complete with catkin_make --pkg
Any ideas what to try?

**Comment by stonier** [comment]
Did the force-cmake succeed? And did you re-source `devel/setup.bash` once done?

**Comment by vliedel** [comment]
force-cmake did succeed (however there is no "built target turtlebot_simulator), source devel/setup.bash didn't help.
When i catkin_make --pkg turtlebot_gazebo, it does run make in the correct dir (turtlebot_simulator/turtlebot_gazebo) without error.

**Comment by SergioMP** [comment]
Hello. Did anyone succeed on the Indigo compilation? Or should I go back to Hydro for the time being?

**Comment by stonier** [comment]
@jihoonl you've been playing around with turtlebots on gazebo in indigo, thoughts on this one?

**Comment by corot** [comment]
For me, all compiled and worked out-of-the-box :neckbeard:

**Comment by mikeferguson** [comment]
It doesn't look like there is anything to "compile" -- once it gets added to the path, it is just a pile of launch files...

**Comment by stonier** [comment]
The kobuki/create plugins underneath need compiling though. From a quick look it appears as if everything is compiling and two people have managed to get gazebo kobuki based turtlebots running without any special hacks.

@vliedel it sounds like you are having a workspace environment problem rather than a turtlebot simulator problem.

Closing this for now, reopen with a new issue if anything specific needs being addressed.
