### ISSUE TITLE
pointcloud_to_laserscan -> depthimage_to_laserscan

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot_simulator#4]
_create.launch
_kobuki.launch

**Comment by corot** [comment]
Cannot run gazebo by now to check what the simulated 3D camera provides: point cloud, depth image or both

**Comment by bit-pirate** [comment]
I would say, just remove it. I'll add it again in case we really need it.

**Comment by bit-pirate** [comment]
I just tested it and it works well - once this bug in the Kinect ROS Gazebo plugin is fixed: https://github.com/ros-simulation/gazebo_ros_pkgs/issues/95.
Currently, that plugin does not publish on the camera info topic, what prevents depthimage_to_laserscan from publishing laserscans.

So, I'll leave it commented out until that bug is resolved.

**Comment by bit-pirate** [comment]
The fixed kinect plugins has been re-released. Issue solved.
