### ISSUE TITLE
Officially release in hydro

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_simulator#9]
This is just a heads up. For now we're removing turtlebot_simulator from the deb releases - it is not officially supported (there are a couple of blocks) and costing us time to keep an eye on the debs on the build farm. 

If you're wanting to workaround the issues, feel free to play with the sources.

If the status quo should magically change, we'll update back here.

**Comment by bit-pirate** [comment]
The Kinect issue is gone. Still there are some Gazebo bugs in our way. Since they are related to the Kobuki simulation, you find a detailed list there: https://github.com/yujinrobot/kobuki_desktop/issues/8

Any Create-related issues will be tracked here: https://github.com/turtlebot/turtlebot_create_desktop/issues/3

**Comment by bit-pirate** [comment]
If possible we should get the issues https://github.com/turtlebot/turtlebot_simulator/issues/1 and https://github.com/turtlebot/turtlebot_simulator/issues/4 fixed as well before the Hydro release:

**Comment by bit-pirate** [comment]
Issue #1 and #4 are solved. Remaining issues can be found in kobuki's and create's desktop repos as mentioned above.

**Comment by bit-pirate** [comment]
Create is more or less working and for Kobuki only wiki doc jobs are left. Release has been triggered as well. So, considering this done.
